# -----------------------------------------------------
# Workflow: Build & Test Java Backend
# EN: Sets up JDK 17, compiles, and tests the backend using Maven Wrapper (./mvnw)
# VI: Thiết lập JDK 17, biên dịch và chạy test cho backend bằng Maven Wrapper (./mvnw)
# Trigger: Runs on push or pull request
# -----------------------------------------------------

name: Build & Test Java Backend

on: [push, pull_request]

jobs:
  build:
    name: 🧱 Compile Backend Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      # Bước 1: Lấy mã nguồn từ repository
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Get full history for versioning metadata

      # Step 2: Set up JDK 17 with Maven dependency caching
      # Bước 2: Cài đặt JDK 17 và bật cache Maven
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # Step 3: Configure UTF-8 encoding for build consistency
      # Bước 3: Thiết lập encoding UTF-8 để tránh lỗi ký tự
      - name: Configure Maven environment
        run: echo "MAVEN_OPTS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      # Step 4: Compile backend using Maven Wrapper
      # Bước 4: Biên dịch mã nguồn bằng Maven Wrapper
      - name: Compile backend
        working-directory: app
        run: |
          chmod +x mvnw
          ./mvnw -B clean compile \
            -Dproject.build.sourceEncoding=UTF-8 \
            -Dproject.reporting.outputEncoding=UTF-8

  test:
    name: ✅ Run Unit Tests
    runs-on: ubuntu-latest
    needs: build  # Ensure compilation completes before testing
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Maven tests
        working-directory: app
        run: |
          chmod +x mvnw
          ./mvnw -B test

  notify:
    name: 📢 Notify on Failure
    runs-on: ubuntu-latest
    needs: [build, test]
    if: failure()
    steps:
      - name: Send failure notification
        run: echo "❌ Build or tests failed. Please review the GitHub Actions logs for details."
