# -----------------------------------------------------
# Workflow: Compile Java Backend
# EN: Sets up JDK 17 and compiles the backend using Maven Wrapper (./mvnw)
# VI: Thiết lập JDK 17 và biên dịch mã nguồn backend bằng Maven Wrapper (./mvnw)
# Trigger: Runs on push or pull request
# -----------------------------------------------------

name: Compile Java Backend

on: [push, pull_request]

jobs:
  compile-backend:
    name: Compile Backend Code
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for accurate build metadata

      # Step 2: Set up JDK 17 with Maven cache
      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven

      # Step 3: Configure UTF-8 encoding
      - name: Configure Maven environment
        run: echo "MAVEN_OPTS=-Dfile.encoding=UTF-8" >> $GITHUB_ENV

      # Step 4: Compile backend using Maven Wrapper
      - name: Compile backend
        working-directory: app
        run: |
          chmod +x mvnw
          ./mvnw -B clean compile \
            -Dproject.build.sourceEncoding=UTF-8 \
            -Dproject.reporting.outputEncoding=UTF-8

      # Step 5: Notify on failure (optional but useful)
      - name: Notify on failure
        if: failure()
        run: echo "❌ Build failed. Please check the compile logs for details."
